apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1 
  template: 
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: badalb/order-service:latest
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8080
          name: management