apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: authz-service
  namespace: routing
spec:
  selector:
    matchLabels:
      app: authz-service
  replicas: 1 
  template: 
    metadata:
      labels:
        app: session-endpoint1
    spec:
      containers:
      - name: authz-service
        image: badalb/authz-service:latest
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8080
          name: management