apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: inventory-service
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: inventory-service
  replicas: 1 
  template: 
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: badalb/inventory-service:latest
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8080
          name: management