---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cfg
  namespace: mongodb
data:
  MONGO-ROOT-USERNAME: root
  MONGO-ROOT-PASSWORD: password
  MONGO-SERVICE-HOST: mongodb-service.mongodb
  MONGO-SERVICE-PORT: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-listener
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 32017
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: singlenode-mongodb-v3
        image: mongo:3.6.5-jessie
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-cfg
              key: MONGO-ROOT-USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mongodb-cfg
              key: MONGO-ROOT-PASSWORD
        ports:
        - containerPort: 27017
          name: listener
      volumes:
      - name: mongodb-data
        hostPath:
          path: /k8s-local-data/mongodb/data
          type: Directory
      nodeSelector:
        mongodb-server: singlenode